# Generated by Django 5.2.13 on 2026-05-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=255)),
                ('ultima_distribuicao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('Alimentos', 'Alimentos'), ('Higiene', 'Higiene'), ('Roupas', 'Roupas')], max_length=30)),
                ('quantidade', models.PositiveIntegerField()),
                ('unidade', models.CharField(max_length=30)),
                ('validade', models.DateField(blank=True, null=True)),
                ('doador', models.CharField(max_length=120)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
