# Generated by Django 5.2.15 on 2026-06-29 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad_app', '0005_novo_beneficiario_e_estoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiado',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Beneficiado', 'verbose_name_plural': 'Beneficiados'},
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='quantidade_doada',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade registrada no momento da doação — nunca alterada.', verbose_name='Quantidade doada (original)'),
        ),
        migrations.RunSQL(
            # Para registros existentes, assume que a quantidade atual é a doada
            sql="UPDATE sigad_app_itemestoque SET quantidade_doada = quantidade WHERE quantidade_doada = 0;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='distribuicao',
            name='beneficiado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuicoes', to='sigad_app.beneficiado', verbose_name='Beneficiado (quem recebeu)'),
        ),
    ]
