# Generated by Django 5.2.15 on 2026-07-06 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad_app', '0007_fix_quantidade_doada_existente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distribuicao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_estoque', to=settings.AUTH_USER_MODEL),
        ),
    ]
